name: React Js (for int) - Create Build and Upload on S3

on:
  workflow_dispatch:
    branches: [int]

  push:
    branches: [int]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Dot.net.files.test.web

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Installing Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"
      - run: npm i
      - run: npm test
      - run: npm run build

      - uses: rishabhkanojiya/aws-copy-rm@remove
        with:
          args: --follow-symlinks --delete
          # args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR_BACKUP: int/season/static-assets/build

      - run: ls

      - uses: rishabhkanojiya/aws-copy-rm@copy
        with:
          args: --follow-symlinks --delete
          # args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR_COPY: ./Dot.net.files.test.web/build
          DEST_DIR_COPY: int/season/static-assets/build
# Both in same job
# jobs:
#   backup:
#     runs-on: ubuntu-latest

#     # steps:
#     #   - uses: actions/checkout@v2
#     #   - uses: rishabhkanojiya/aws-copy-rm@main
#     #     with:
#     #       args: --follow-symlinks --delete
#     #       # args: --acl public-read --follow-symlinks --delete
#     #     env:
#     #       AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
#     #       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#     #       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#     #       SOURCE_DIR: ${{ secrets.DEST_DIR }}
#     #       DEST_DIR: ${{ secrets.BACKUP_DIR }}

#     strategy:
#       matrix:
#         node-version: [14.x]

#     steps:
#       - uses: actions/checkout@v2
#       - uses: rishabhkanojiya/aws-copy-rm@main
#         with:
#           args: --follow-symlinks --delete
#           # args: --acl public-read --follow-symlinks --delete
#         env:
#           AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           SOURCE_DIR: ${{ secrets.DEST_DIR }}
#           DEST_DIR: ${{ secrets.BACKUP_DIR }}

#       - uses: actions/checkout@v2
#       - name: Use Node.js ${{ matrix.node-version }}
#         uses: actions/setup-node@v2
#         with:
#           node-version: ${{ matrix.node-version }}
#           cache: "npm"
#       - run: npm i
#       - run: npm test
#       - run: npm run build
#       - uses: jakejarvis/s3-sync-action@master
#         with:
#           args: --follow-symlinks --delete
#           # args: --acl public-read --follow-symlinks --delete
#         env:
#           AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           SOURCE_DIR: ${{ secrets.SOURCE_DIR }}
#           DEST_DIR: ${{ secrets.DEST_DIR }}
