name: React Js (for Prod) - Create Build and Upload on S3

on:
  workflow_dispatch:
    branches: [main]

  push:
    branches: [main, prod]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm i
      - run: npm test
      - run: npm run build

      - uses: rishabhkanojiya/aws-copy-rm@backup
        with:
          args: --follow-symlinks --delete
          # args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # SOURCE_DIR_BACKUP: ${{ secrets.PROD_BACKUP_SOURCE_DIR }}
          # DEST_DIR_BACKUP: ${{ secrets.PROD_BACKUP_DEST_DIR }}
          # SOURCE_DIR_COPY: ${{ secrets.PROD_SOURCE_DIR }}
          # DEST_DIR_COPY: ${{ secrets.PORD_DEST_DIR }}
          SOURCE_DIR_BACKUP: prod/season/static-assets/build
          DEST_DIR_BACKUP: prod/season/static-assets/backup
          SOURCE_DIR_COPY: ./build
          DEST_DIR_COPY: prod/season/static-assets/build

      # - uses: rishabhkanojiya/aws-copy-rm@remove
      #   with:
      #     args: --follow-symlinks --delete
      #     # args: --acl public-read --follow-symlinks --delete
      #   env:
      #     AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     SOURCE_DIR: ${{ secrets.PROD_BACKUP_SOURCE_DIR }}

      # - uses: rishabhkanojiya/aws-copy-rm@copy
      #   with:
      #     args: --follow-symlinks --delete
      #     # args: --acl public-read --follow-symlinks --delete
      #   env:
      #     AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     SOURCE_DIR_PROD: ${{ secrets.PROD_SOURCE_DIR }}
      #     DEST_DIR_PROD: ${{ secrets.PORD_DEST_DIR }}

    #       diff backup and remove job
    #         backup:
    # runs-on: ubuntu-latest

    # steps:
    #   - uses: actions/checkout@v2
    #   - uses: rishabhkanojiya/aws-copy-rm@backup
    #     with:
    #       args: --follow-symlinks --delete
    #       # args: --acl public-read --follow-symlinks --delete
    #     env:
    #       AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
    #       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #       SOURCE_DIR: ${{ secrets.PROD_BACKUP_SOURCE_DIR }}
    #       DEST_DIR: ${{ secrets.PROD_BACKUP_DEST_DIR }}

    #   - uses: rishabhkanojiya/aws-copy-rm@remove
    #     with:
    #       args: --follow-symlinks --delete
    #       # args: --acl public-read --follow-symlinks --delete
    #     env:
    #       AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
    #       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #       SOURCE_DIR: ${{ secrets.PROD_BACKUP_SOURCE_DIR }}
# Both in same job
# jobs:
#   backup:
#     runs-on: ubuntu-latest

#     # steps:
#     #   - uses: actions/checkout@v2
#     #   - uses: rishabhkanojiya/aws-copy-rm@main
#     #     with:
#     #       args: --follow-symlinks --delete
#     #       # args: --acl public-read --follow-symlinks --delete
#     #     env:
#     #       AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
#     #       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#     #       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#     #       SOURCE_DIR: ${{ secrets.DEST_DIR }}
#     #       DEST_DIR: ${{ secrets.BACKUP_DIR }}

#     strategy:
#       matrix:
#         node-version: [14.x]

#     steps:
#       - uses: actions/checkout@v2
#       - uses: rishabhkanojiya/aws-copy-rm@main
#         with:
#           args: --follow-symlinks --delete
#           # args: --acl public-read --follow-symlinks --delete
#         env:
#           AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           SOURCE_DIR: ${{ secrets.DEST_DIR }}
#           DEST_DIR: ${{ secrets.BACKUP_DIR }}

#       - uses: actions/checkout@v2
#       - name: Use Node.js ${{ matrix.node-version }}
#         uses: actions/setup-node@v2
#         with:
#           node-version: ${{ matrix.node-version }}
#           cache: "npm"
#       - run: npm i
#       - run: npm test
#       - run: npm run build
#       - uses: jakejarvis/s3-sync-action@master
#         with:
#           args: --follow-symlinks --delete
#           # args: --acl public-read --follow-symlinks --delete
#         env:
#           AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           SOURCE_DIR: ${{ secrets.SOURCE_DIR }}
#           DEST_DIR: ${{ secrets.DEST_DIR }}
