name: React Js - Create Build and Upload on S3

on:
  workflow_dispatch:
    branches: [main]

  push:
    branches: [main]

jobs:
  backup:
    runs-on: ubuntu-latest

    # steps:
    #   - uses: actions/checkout@v2
    #   - uses: rishabhkanojiya/aws-copy-rm@main
    #     with:
    #       args: --follow-symlinks --delete
    #       # args: --acl public-read --follow-symlinks --delete
    #     env:
    #       AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
    #       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #       SOURCE_DIR: ${{ secrets.DEST_DIR }}
    #       DEST_DIR: ${{ secrets.BACKUP_DIR }}

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - uses: rishabhkanojiya/aws-copy-rm@main
        with:
          args: --follow-symlinks --delete
          # args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: ${{ secrets.DEST_DIR }}
          DEST_DIR: ${{ secrets.BACKUP_DIR }}

      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm i
      - run: npm test
      - run: npm run build
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --follow-symlinks --delete
          # args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: ${{ secrets.SOURCE_DIR }}
          DEST_DIR: ${{ secrets.DEST_DIR }}

  # build:
  #   needs: backup
  #   runs-on: ubuntu-latest

  #   strategy:
  #     matrix:
  #       node-version: [14.x]

  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Use Node.js ${{ matrix.node-version }}
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #         cache: "npm"
  #     - run: npm i
  #     - run: npm test
  #     - run: npm run build
  #     - uses: jakejarvis/s3-sync-action@master
  #       with:
  #         args: --follow-symlinks --delete
  #         # args: --acl public-read --follow-symlinks --delete
  #       env:
  #         AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
  #         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         SOURCE_DIR: ${{ secrets.SOURCE_DIR }}
  #         DEST_DIR: ${{ secrets.DEST_DIR }}
