name: Removing and Copying Files

on:
  workflow_call:
    inputs:
      args:
        required: true
        type: string
      shouldRun:
        required: true
        type: string
      version:
        required: true
        type: string
      IS_PROD:
        required: true
        type: string
      IS_RM:
        type: string

    secrets:
      AWS_S3_BUCKET:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      SOURCE_DIR:
        required: true
      DEST_DIR:
        required: true
      BACKUP_SOURCE_DIR:
        required: true
      BACKUP_DEST_DIR:
        required: true

jobs:
  DeployDev:
    name: Deploy
    if: ${{ inputs.shouldRun == 'true' }}
    runs-on: ubuntu-latest

    environment:
      name: ${{ inputs.IS_PROD == 'true' && 'Production' || 'Dev'}}
      url: ${{ inputs.IS_PROD == 'true' && 'https://prod.com' || 'https://dev.com'}}

    #  Using the "Dev" environment setting for environment variables and protection rules

    defaults:
      run:
        working-directory: Dot.net.files.test.web

    steps:
      - uses: actions/checkout@v3

      - name: Restoring Build Cache
        id: cache-react-build
        uses: actions/cache@v3
        with:
          path: |
            **/build
          key: ${{ runner.os }}-cache-react-build-${{ inputs.version }}
      # restoring the cached build from "Step: Cache Build"

      - run: ls
      - id: rem_copy
        name: Remove Old Build And Copy New Build
        run: bash ./public/deploy/build.sh
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR_COPY: ./build
          DEST_DIR_COPY: ${{ secrets.DEST_DIR }}
          SOURCE_DIR_BACKUP: ${{ secrets.BACKUP_SOURCE_DIR }}
          DEST_DIR_BACKUP: ${{ secrets.BACKUP_DEST_DIR }}
          args: ${{ inputs.args }}
          IS_PROD: ${{ inputs.IS_PROD }}
          IS_RM: ${{ inputs.IS_RM }}
