name: Removing and Copying Files (using script)

on:
  workflow_call:
    inputs:
      args:
        required: true
        type: string
      shouldRun:
        required: true
        type: string
      version:
        required: true
        type: string
      IS_PROD:
        required: true
        type: string
      IS_RM:
        type: string

    secrets:
      AWS_S3_BUCKET:
        required: true
      SOURCE_DIR:
        required: true
      DEST_DIR:
        required: true
      BACKUP_SOURCE_DIR:
        required: true
      BACKUP_DEST_DIR:
        required: true
      PROD_S3_KEY:
        required: true
      INT_S3_KEY:
        required: true
      PROD_SECRET_KEY:
        required: true
      INT_SECRET_KEY:
        required: true

jobs:
  DeployDev:
    name: Deploy
    if: ${{ inputs.shouldRun == 'true' }}
    runs-on: ubuntu-latest

    environment:
      name: ${{ inputs.IS_PROD == 'true' && 'Production' || 'Dev'}}
      url: ${{ inputs.IS_PROD == 'true' && 'https://prod.com' || 'https://dev.com'}}

    #  Using the "Dev" environment setting for environment variables and protection rules

    # defaults:
    #   run:
    #     working-directory: Dot.net.files.test.web
    # "defaults" and "working-directory: Dot.net.files.test.web" are used here so that the job can look in this folder for the "package.json" file.

    steps:
      - uses: actions/checkout@v3

      - name: Restoring Build Cache
        id: cache-react-build
        uses: actions/cache@v3
        with:
          path: |
            **/build
          key: ${{ runner.os }}-cache-react-build-${{ inputs.version }}
      # restoring the cached build from "Step: Cache Build"

      - id: rem_copy
        name: Remove Old Build And Copy New Build
        run: bash ./public/deploy/build.sh
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ inputs.IS_PROD == 'true' && secrets.PROD_S3_KEY || secrets.INT_S3_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ inputs.IS_PROD == 'true' && secrets.PROD_SECRET_KEY || secrets.INT_SECRET_KEY }}
          SOURCE_DIR_COPY: ./build
          DEST_DIR_COPY: ${{ secrets.DEST_DIR }}
          SOURCE_DIR_BACKUP: ${{ secrets.BACKUP_SOURCE_DIR }}
          DEST_DIR_BACKUP: ${{ secrets.BACKUP_DEST_DIR }}
          args: ${{ inputs.args }}
          IS_PROD: ${{ inputs.IS_PROD }}
          IS_RM: ${{ inputs.IS_RM }}
