name: Send Message on Slack

on:
  workflow_call:
    secrets:
      SLACK_WEBHOOK:
        required: true
# on:
#   workflow_dispatch:
#     branches: [main]

#   push:
#     branches: [test]

jobs:
  slackMessage:
    name: Get Data for slack Message
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - id: set-result
        name: Generate a status for Slack
        uses: actions/github-script@v6
        with:
          script: |
            const makePayload = (data, jobDetails) => {
              let status = false;
              let commit = data?.head_commit?.message;
              let isFailed = jobDetails?.jobs.find((job) => job.conclusion === "failure");
              if (isFailed) {
                status = true;
                commit = `Failed at '${isFailed.name}' @${data?.actor?.login}`;
              }

              return {
                name: data?.name,
                userName: data?.actor?.login,
                userImage: data?.actor?.avatar_url,
                runs: data?.run_number,
                status,
                commit
              };
            };

            const runDetails = await github.rest.actions.getWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context?.runId,
            });

            const jobDetails = await github.rest.actions.listJobsForWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context?.runId,
            });


            const data = makePayload(runDetails?.data, jobDetails?.data);

            return data;
      - run: echo "${{fromJson(steps.set-result.outputs.result).userName}}"
      - run: echo "${{fromJson(steps.set-result.outputs.result).status}}"
      - run: echo "${{fromJson(steps.set-result.outputs.result).commit}}"

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_FOOTER: ""
          SLACK_USERNAME: Notification
          SLACK_MSG_AUTHOR: ${{fromJson(steps.set-result.outputs.result).userName}}
          SLACK_COLOR: "${{ fromJson(steps.set-result.outputs.result).status == true && '#ee6055' || '#60d394' }}"
          SLACK_TITLE: "${{ fromJson(steps.set-result.outputs.result).status == true && '❌ Build Upload Failed' || '🚀 Build Uploaded Successfully' }}"
          SLACK_MESSAGE: "${{ fromJson(steps.set-result.outputs.result).commit }}"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

    # This section simply notifies a slack channel when the process fails or pass.
    # The message contains the following information:
    # 1. the user who initiated the actions.
    # 2. the branch that is currently being pushed
    # 3. the action that is being performed
    # 4. final commit message
